# Generated by Django 5.2 on 2025-04-28 21:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransaccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_transaccion', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('forma_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Banco', 'Banco')], max_length=10, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('Pesos', 'Pesos'), ('Dolares', 'Dolares')], max_length=10, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('deuda', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('archivo', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contacto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.contacto')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.cuentabancaria')),
                ('cuentas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.cuentas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogos.proyecto')),
            ],
            options={
                'verbose_name': 'historical transaccion',
                'verbose_name_plural': 'historical transaccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_transaccion', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('forma_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Banco', 'Banco')], max_length=10, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('Pesos', 'Pesos'), ('Dolares', 'Dolares')], max_length=10, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.TextField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('deuda', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='transacciones/')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_principal', to='catalogos.contacto')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.cuentabancaria')),
                ('cuentas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.cuentas')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.proyecto')),
            ],
        ),
    ]
